title: BIGBIGPLANTS
description: >- 
  Hydroponics, Biogas reactors, Botany!
baseurl: ""
url: ""
github_username:  bigbigplants

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - kramdown

math_engine: katex
