title: BIGBIGPLANTS
description: >- 
  hydroponics, biogas reactors, botany!
baseurl: ""
url: ""
github_username:  bigbigplants

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - kramdown
  - jekyll-scholar

collections:
  chapters:
    output: true

scholar:
  bibliography: references.bib
  style: _bibliography/ieee.csl

math_engine: katex
